-- =========================================================
-- Archron — SYNC ALL (ไฟล์เดียวจบ — ทุก table, trigger, index, RLS, grant)
-- คัดลอกทั้งหมด → Supabase SQL Editor → Run
-- Idempotent — รันซ้ำได้ปลอดภัย
-- =========================================================

create extension if not exists "pgcrypto";

-- =========================================================
-- 1) entries — ตารางหลักเก็บเนื้อหาทุกประเภท
-- =========================================================
create table if not exists public.entries (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  title text not null,
  status text not null default 'draft',
  content_type text not null default 'article',
  author_id text not null,
  author_name text,

  -- identity block
  main_term text,
  thai_name text,
  original_term text,
  part_of_speech text,
  language_root text,
  ipa text,
  short_description text,

  -- framework / theory
  framework text,
  main_thinkers text[],
  school text,
  difficulty text,
  tags text[],

  -- specialized content type fields (person, book, school, article)
  subtitle text,
  series text,
  volume text,
  aliases text[],
  born_year text,
  died_year text,
  nationality text,
  key_ideas text[],
  notable_works text[],
  publication_year text,
  publisher text,
  isbn text,
  founder text,
  period text,
  real_world_examples text,

  -- content (reading body)
  visual_explanation text,
  technical_meaning text,
  body_markdown text,
  cover_image text,
  r2_content_key text,
  r2_content_url text,

  -- row metadata (auto-generated by trigger)
  row_id uuid default gen_random_uuid(),
  row_i integer,
  row_code text,
  row_name text,

  -- structured (jsonb)
  roots jsonb,
  related_concepts jsonb not null default '[]'::jsonb,
  source_refs jsonb not null default '[]'::jsonb,
  related_cta jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

-- =========================================================
-- 1b) entries — เพิ่มคอลัมน์ที่อาจขาด (ถ้าตารางมีอยู่แล้ว)
-- =========================================================
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS author_name text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS r2_content_key text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS r2_content_url text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS row_id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS row_i integer;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS row_code text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS row_name text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS subtitle text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS series text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS volume text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS aliases text[];
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS born_year text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS died_year text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS nationality text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS key_ideas text[];
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS notable_works text[];
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS publication_year text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS publisher text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS isbn text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS founder text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS period text;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS real_world_examples text;

-- row_id unique constraint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'entries_row_id_unique'
  ) THEN
    ALTER TABLE public.entries ADD CONSTRAINT entries_row_id_unique UNIQUE (row_id);
  END IF;
END $$;

-- =========================================================
-- 2) entry_revisions — version history
-- =========================================================
create table if not exists public.entry_revisions (
  id uuid primary key default gen_random_uuid(),
  entry_id uuid not null references public.entries(id) on delete cascade,
  snapshot jsonb not null,
  created_by text not null,
  note text,
  created_at timestamptz not null default now()
);

-- =========================================================
-- 3) profiles — user profile (role in Clerk publicMetadata)
-- =========================================================
create table if not exists public.profiles (
  clerk_user_id text primary key,
  username text unique,
  display_name text,
  title text,
  writer_request boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================================================
-- 4) comments — article/concept comments
-- =========================================================
create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  section text not null,
  slug text not null,
  clerk_user_id text not null,
  author_name text,
  body text not null,
  status text not null default 'visible',
  parent_id text references public.comments(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- migration: สำหรับตารางที่มีอยู่แล้วที่ยังไม่มี parent_id
alter table public.comments add column if not exists parent_id text references public.comments(id) on delete cascade;

-- =========================================================
-- 5) page_views — visit counter
-- =========================================================
create table if not exists public.page_views (
  slug text primary key,
  views bigint not null default 0,
  updated_at timestamptz not null default now()
);

-- =========================================================
-- 6) reading_progress — per-user reading progress
-- =========================================================
create table if not exists public.reading_progress (
  clerk_user_id text not null,
  slug text not null,
  content_type text not null default 'article',
  status text not null default 'reading',
  progress smallint not null default 0,
  first_read_at timestamptz default now(),
  completed_at timestamptz,
  updated_at timestamptz default now(),
  primary key (clerk_user_id, slug)
);

-- =========================================================
-- 7) user_achievements — badges/achievements
-- =========================================================
create table if not exists public.user_achievements (
  clerk_user_id text not null,
  achievement_key text not null,
  unlocked_at timestamptz default now(),
  primary key (clerk_user_id, achievement_key)
);

-- =========================================================
-- 8) library — RTK library (search index)
-- =========================================================
create table if not exists public.library (
  id uuid primary key default gen_random_uuid(),
  entry_id uuid unique not null references public.entries(id) on delete cascade,
  title text not null,
  slug text unique not null,
  summary text,
  category text,
  tags text[] default '{}',
  language text not null default 'th',
  author text,
  token_count integer not null default 0,
  hash text,
  r2_key text,
  fts tsvector,
  updated_at timestamptz not null default now(),
  indexed_at timestamptz not null default now()
);

-- =========================================================
-- 9) chunks — RTK chunks (searchable segments)
-- =========================================================
create table if not exists public.chunks (
  id uuid primary key default gen_random_uuid(),
  library_id uuid not null references public.library(id) on delete cascade,
  chunk_no integer not null,
  heading text,
  summary text,
  token_count integer not null default 0,
  r2_key text not null,
  fts tsvector,
  created_at timestamptz not null default now(),
  unique(library_id, chunk_no)
);

-- =========================================================
-- INDEXES
-- =========================================================
create index if not exists entries_author_idx on public.entries (author_id);
create index if not exists entries_author_name_idx on public.entries (author_name);
-- partial index สำหรับ query ที่บ่อยที่สุด (ไม่ต้อง scan ทั้งตาราง)
drop index if exists public.entries_status_idx;
create index if not exists entries_published_idx on public.entries (published_at desc) where status = 'published';
create index if not exists entries_row_code_idx on public.entries (row_code);
create index if not exists entries_row_i_idx on public.entries (content_type, row_i);
create index if not exists entries_row_id_idx on public.entries (row_id);
create index if not exists rev_entry_idx on public.entry_revisions (entry_id);
create index if not exists profiles_username_idx on public.profiles (username);
create index if not exists comments_target_idx on public.comments (section, slug, created_at);
create index if not exists comments_user_idx on public.comments (clerk_user_id);
create index if not exists comments_parent_idx on public.comments (parent_id);
create index if not exists reading_progress_user_status_idx on public.reading_progress (clerk_user_id, status);
create index if not exists user_achievements_user_idx on public.user_achievements (clerk_user_id);
create index if not exists library_fts_idx on public.library using gin (fts);
create index if not exists library_slug_idx on public.library (slug);
create index if not exists library_category_idx on public.library (category);
create index if not exists library_indexed_at_idx on public.library (indexed_at desc);
create index if not exists chunks_fts_idx on public.chunks using gin (fts);
create index if not exists chunks_library_idx on public.chunks (library_id);
-- FK indexes สำหรับ CASCADE delete/UPDATE
create index if not exists page_views_slug_idx on public.page_views (slug);

-- =========================================================
-- TRIGGER FUNCTION: updated_at
-- =========================================================
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end; $$;

-- =========================================================
-- TRIGGER FUNCTION: auto row_id / row_i / row_code
-- =========================================================
create or replace function public.entries_auto_row_code()
returns trigger language plpgsql as $$
declare
  prefix text;
  next_i integer;
begin
  if new.row_i is not null and new.row_code is not null then
    return new;
  end if;

  if new.row_id is null then
    new.row_id := gen_random_uuid();
  end if;

  prefix := case new.content_type
    when 'article'      then 'ART'
    when 'concept'      then 'CON'
    when 'reading-set'  then 'RDS'
    when 'source-note'  then 'SRC'
    when 'person'       then 'THK'
    when 'book'         then 'BOK'
    when 'school'       then 'SCH'
    when 'symbol'       then 'SYM'
    when 'term'         then 'TRM'
    else 'ENT'
  end;

  select coalesce(max(row_i), 0) + 1 into next_i
  from public.entries
  where content_type = new.content_type;

  new.row_i    := next_i;
  new.row_code := prefix || '-' || lpad(next_i::text, 3, '0');
  new.row_name := coalesce(new.row_name, new.title);

  return new;
end;
$$;

-- =========================================================
-- TRIGGER FUNCTION: library FTS
-- =========================================================
create or replace function public.library_fts_trigger()
returns trigger language plpgsql as $$
begin
  new.fts :=
    setweight(to_tsvector('simple', coalesce(new.title,'')), 'A')
    || setweight(to_tsvector('simple', coalesce(new.slug,'')), 'B')
    || setweight(to_tsvector('simple', coalesce(array_to_string(new.tags,' '),'')), 'B')
    || setweight(to_tsvector('simple', coalesce(new.summary,'')), 'C');
  return new;
end;
$$;

-- =========================================================
-- TRIGGER FUNCTION: chunks FTS
-- =========================================================
create or replace function public.chunks_fts_trigger()
returns trigger language plpgsql as $$
begin
  new.fts :=
    setweight(to_tsvector('simple', coalesce(new.heading,'')), 'B')
    || setweight(to_tsvector('simple', coalesce(new.summary,'')), 'C');
  return new;
end;
$$;

-- =========================================================
-- TRIGGERS: attach to tables
-- =========================================================
drop trigger if exists entries_set_updated_at on public.entries;
create trigger entries_set_updated_at
  before update on public.entries
  for each row execute function public.set_updated_at();

drop trigger if exists entries_auto_row_code on public.entries;
create trigger entries_auto_row_code
  before insert on public.entries
  for each row execute function public.entries_auto_row_code();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists reading_progress_set_updated_at on public.reading_progress;
create trigger reading_progress_set_updated_at
  before update on public.reading_progress
  for each row execute function public.set_updated_at();

drop trigger if exists library_set_updated_at on public.library;
create trigger library_set_updated_at
  before update on public.library
  for each row execute function public.set_updated_at();

drop trigger if exists trg_library_fts on public.library;
create trigger trg_library_fts
  before insert or update on public.library
  for each row execute function public.library_fts_trigger();

drop trigger if exists trg_chunks_fts on public.chunks;
create trigger trg_chunks_fts
  before insert or update on public.chunks
  for each row execute function public.chunks_fts_trigger();

-- =========================================================
-- FOREIGN KEYS
-- =========================================================
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where constraint_name = 'comments_slug_fkey' and table_name = 'comments'
  ) then
    alter table public.comments
      add constraint comments_slug_fkey
      foreign key (slug) references public.entries(slug)
      on delete cascade;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where constraint_name = 'page_views_slug_fkey' and table_name = 'page_views'
  ) then
    alter table public.page_views
      add constraint page_views_slug_fkey
      foreign key (slug) references public.entries(slug)
      on delete cascade;
  end if;
end $$;

-- =========================================================
-- RLS — Enable
-- =========================================================
alter table public.entries enable row level security;
alter table public.entry_revisions enable row level security;
alter table public.profiles enable row level security;
alter table public.comments enable row level security;
alter table public.page_views enable row level security;
alter table public.reading_progress enable row level security;
alter table public.user_achievements enable row level security;
alter table public.library enable row level security;
alter table public.chunks enable row level security;

-- =========================================================
-- RLS — Policies: entries
-- =========================================================
drop policy if exists entries_select on public.entries;
create policy entries_select on public.entries
  for select using (status = 'published' or author_id = (auth.jwt()->>'sub'));

drop policy if exists entries_insert on public.entries;
create policy entries_insert on public.entries
  for insert with check (author_id = (auth.jwt()->>'sub'));

drop policy if exists entries_update on public.entries;
create policy entries_update on public.entries
  for update using (author_id = (auth.jwt()->>'sub'))
  with check (author_id = (auth.jwt()->>'sub'));

drop policy if exists entries_delete on public.entries;
create policy entries_delete on public.entries
  for delete using (author_id = (auth.jwt()->>'sub'));

-- =========================================================
-- RLS — Policies: entry_revisions
-- =========================================================
drop policy if exists rev_all_own on public.entry_revisions;
create policy rev_all_own on public.entry_revisions
  for all using (
    exists (
      select 1 from public.entries e
      where e.id = entry_id and e.author_id = (auth.jwt()->>'sub')
    )
  )
  with check (created_by = (auth.jwt()->>'sub'));

-- =========================================================
-- RLS — Policies: profiles
-- =========================================================
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
  for select using (true);

drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles
  for insert with check (clerk_user_id = (auth.jwt()->>'sub'));

drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles
  for update using (clerk_user_id = (auth.jwt()->>'sub'))
  with check (clerk_user_id = (auth.jwt()->>'sub'));

-- =========================================================
-- RLS — Policies: comments
-- =========================================================
drop policy if exists comments_select on public.comments;
create policy comments_select on public.comments
  for select using (status = 'visible' or clerk_user_id = (auth.jwt()->>'sub'));

drop policy if exists comments_insert on public.comments;
create policy comments_insert on public.comments
  for insert with check (clerk_user_id = (auth.jwt()->>'sub'));

drop policy if exists comments_update on public.comments;
create policy comments_update on public.comments
  for update using (clerk_user_id = (auth.jwt()->>'sub'))
  with check (clerk_user_id = (auth.jwt()->>'sub'));

drop policy if exists comments_delete on public.comments;
create policy comments_delete on public.comments
  for delete using (clerk_user_id = (auth.jwt()->>'sub'));

-- =========================================================
-- RLS — Policies: page_views
-- =========================================================
drop policy if exists page_views_select on public.page_views;
create policy page_views_select on public.page_views
  for select using (true);

-- =========================================================
-- RLS — Policies: reading_progress
-- =========================================================
drop policy if exists reading_progress_select on public.reading_progress;
create policy reading_progress_select on public.reading_progress
  for select using (clerk_user_id = (auth.jwt()->>'sub'));

drop policy if exists reading_progress_insert on public.reading_progress;
create policy reading_progress_insert on public.reading_progress
  for insert with check (clerk_user_id = (auth.jwt()->>'sub'));

drop policy if exists reading_progress_update on public.reading_progress;
create policy reading_progress_update on public.reading_progress
  for update using (clerk_user_id = (auth.jwt()->>'sub'))
  with check (clerk_user_id = (auth.jwt()->>'sub'));

drop policy if exists reading_progress_delete on public.reading_progress;
create policy reading_progress_delete on public.reading_progress
  for delete using (clerk_user_id = (auth.jwt()->>'sub'));

-- =========================================================
-- RLS — Policies: user_achievements
-- =========================================================
drop policy if exists user_achievements_select on public.user_achievements;
create policy user_achievements_select on public.user_achievements
  for select using (clerk_user_id = (auth.jwt()->>'sub'));

drop policy if exists user_achievements_insert on public.user_achievements;
create policy user_achievements_insert on public.user_achievements
  for insert with check (clerk_user_id = (auth.jwt()->>'sub'));

drop policy if exists user_achievements_update on public.user_achievements;
create policy user_achievements_update on public.user_achievements
  for update using (clerk_user_id = (auth.jwt()->>'sub'))
  with check (clerk_user_id = (auth.jwt()->>'sub'));

drop policy if exists user_achievements_delete on public.user_achievements;
create policy user_achievements_delete on public.user_achievements
  for delete using (clerk_user_id = (auth.jwt()->>'sub'));

-- =========================================================
-- RLS — Policies: library + chunks (read-only public)
-- =========================================================
drop policy if exists library_select on public.library;
create policy library_select on public.library
  for select using (true);

drop policy if exists chunks_select on public.chunks;
create policy chunks_select on public.chunks
  for select using (true);

-- =========================================================
-- 10) collections — คอลเลกชัน/เส้นทางการอ่าน
-- =========================================================
create table if not exists public.collections (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  type text not null default 'curated' check (type in ('series', 'pathway', 'curated', 'auto', 'temporal')),
  description text,
  cover_url text,
  is_published boolean default false,
  sort_order int default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.collections is 'คอลเลกชัน/เส้นทางการอ่าน (series, pathway, etc.)';

-- =========================================================
-- 11) collection_entries — ความสัมพันธ์ระหว่าง collections กับ entries
-- =========================================================
create table if not exists public.collection_entries (
  collection_id uuid not null references public.collections(id) on delete cascade,
  entry_id uuid not null references public.entries(id) on delete cascade,
  sort_order int default 0,
  notes text,
  created_at timestamptz not null default now(),
  primary key (collection_id, entry_id)
);

comment on table public.collection_entries is 'รายการ entries ในแต่ละคอลเลกชัน';

-- =========================================================
-- collections — indexes
-- =========================================================
create index if not exists collections_slug_idx on public.collections (slug);
create index if not exists collections_type_idx on public.collections (type);
create index if not exists collection_entries_entry_idx on public.collection_entries (entry_id);
create index if not exists collection_entries_collection_idx on public.collection_entries (collection_id);

-- =========================================================
-- collections — triggers
-- =========================================================
drop trigger if exists collections_set_updated_at on public.collections;
create trigger collections_set_updated_at
  before update on public.collections
  for each row execute function public.set_updated_at();

-- =========================================================
-- collections — RLS
-- =========================================================
alter table public.collections enable row level security;
alter table public.collection_entries enable row level security;

drop policy if exists collections_select on public.collections;
create policy collections_select on public.collections
  for select using (is_published = true);

drop policy if exists collection_entries_select on public.collection_entries;
create policy collection_entries_select on public.collection_entries
  for select using (
    collection_id in (select id from public.collections where is_published = true)
  );

-- =========================================================
-- collections — GRANTS
-- =========================================================
grant select on public.collections to anon, authenticated;
grant insert, update, delete on public.collections to authenticated;
grant select on public.collection_entries to anon, authenticated;
grant insert, update, delete on public.collection_entries to authenticated;

-- =========================================================
-- GRANTS — table-level access
-- =========================================================
grant select on public.entries to anon, authenticated;
grant insert, update, delete on public.entries to authenticated;
grant select, insert, update, delete on public.entry_revisions to authenticated;
grant select on public.profiles to anon, authenticated;
grant insert, update on public.profiles to authenticated;
grant select on public.comments to anon, authenticated;
grant insert, update, delete on public.comments to authenticated;
grant select on public.page_views to anon, authenticated;
grant select, insert, update, delete on public.reading_progress to authenticated;
grant select, insert, update, delete on public.user_achievements to authenticated;
grant select on public.library to anon, authenticated;
grant select on public.chunks to anon, authenticated;

-- =========================================================
-- RPC FUNCTIONS
-- =========================================================

-- increment page view (+1)
create or replace function public.increment_page_view(p_slug text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_views bigint;
begin
  insert into public.page_views (slug, views, updated_at)
  values (p_slug, 1, now())
  on conflict (slug)
  do update set views = public.page_views.views + 1, updated_at = now()
  returning views into new_views;
  return new_views;
end; $$;

-- total page views
create or replace function public.total_page_views()
returns bigint
language sql
security definer
set search_path = public
as $$
  select coalesce(sum(views), 0)::bigint from public.page_views;
$$;

-- search library FTS
create or replace function public.search_library_fts(
  p_q text,
  p_limit integer default 5
)
returns setof public.library
language sql stable
set search_path = public
as $$
  select * from public.library
  where fts @@ plainto_tsquery('simple', p_q)
  order by ts_rank(fts, plainto_tsquery('simple', p_q)) desc
  limit p_limit;
$$;

-- search chunks FTS
create or replace function public.search_chunks_fts(
  p_q text,
  p_limit integer default 5
)
returns setof public.chunks
language sql stable
set search_path = public
as $$
  select * from public.chunks
  where fts @@ plainto_tsquery('simple', p_q)
  order by ts_rank(fts, plainto_tsquery('simple', p_q)) desc
  limit p_limit;
$$;

grant execute on function public.increment_page_view(text) to anon, authenticated;
grant execute on function public.total_page_views() to anon, authenticated;
grant execute on function public.search_library_fts(text, integer) to anon, authenticated;
grant execute on function public.search_chunks_fts(text, integer) to anon, authenticated;

-- =========================================================
-- BACKFILL — สร้าง row_id/row_i/row_code ให้ row เก่า
-- =========================================================
do $$
declare
  r record;
  prefix text;
  counter integer;
  ct record;
begin
  for ct in
    select distinct content_type from public.entries where row_i is null order by content_type
  loop
    counter := 0;
    prefix := case ct.content_type
      when 'article'      then 'ART'
      when 'concept'      then 'CON'
      when 'reading-set'  then 'RDS'
      when 'source-note'  then 'SRC'
      when 'person'       then 'THK'
      when 'book'         then 'BOK'
      when 'school'       then 'SCH'
      when 'symbol'       then 'SYM'
      when 'term'         then 'TRM'
      else 'ENT'
    end;

    for r in
      select id, title from public.entries
      where content_type = ct.content_type and row_i is null
      order by created_at
    loop
      counter := counter + 1;
      update public.entries
      set row_id   = coalesce(row_id, gen_random_uuid()),
          row_i    = counter,
          row_code = prefix || '-' || lpad(counter::text, 3, '0'),
          row_name = coalesce(row_name, title)
      where id = r.id;
    end loop;
  end loop;
end;
$$;

-- =========================================================
-- RPC: get_comment_subtree — recursive CTE for reply threads
-- =========================================================
create or replace function get_comment_subtree(root_id text)
returns setof public.comments as $$
  with recursive tree as (
    select * from public.comments where id = root_id and status = 'visible'
    union all
    select c.* from public.comments c
    join tree t on c.parent_id = t.id
    where c.status = 'visible'
  )
  select * from tree;
$$ language sql stable;

-- =========================================================
-- DONE — ตรวจสอบผลลัพธ์
-- =========================================================
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public' ORDER BY table_name;
--
-- ตารางทั้ง 11: chunks, collection_entries, collections, comments,
--                entries, entry_revisions, library, page_views,
--                profiles, reading_progress, user_achievements
