// Concept Registry (Phase 7) — ฐานกลางของแนวคิด/นักคิด/หนังสือ/สำนัก/สัญลักษณ์/คำศัพท์
// ใช้เป็นฐานของ related concepts, backlinks, internal link suggestions และ Constellation Map

export type NodeType =
  | "concept"
  | "person"
  | "book"
  | "school"
  | "symbol"
  | "term";

export type ConceptRegistryItem = {
  id: string;
  title: string;
  slug: string;
  thaiTitle?: string;
  aliases: string[];
  nodeType: NodeType;
  framework?: string;
  description?: string;
};

// สำนักคิดทั้งหมด (school nodes) — auto-generated ให้ตรงกับ entries (content_type=school) ใน Supabase
const schoolRegistry: ConceptRegistryItem[] = [
  {
    id: "school-adlerian",
    title: "Adlerian",
    slug: "adlerian",
    thaiTitle: "จิตวิทยาแอดเลอร์ / จิตวิทยาปัจเจกบุคคล",
    aliases: ["Adlerian", "จิตวิทยาปัจเจกบุคคล", "จิตวิทยาแอดเลอร์", "จิตวิทยาแอดเลอร์ / จิตวิทยาปัจเจกบุคคล"],
    nodeType: "school",
    description: "สำนักที่เน้นความรู้สึกด้อยกว่า (Inferiority) และแรงขับสู่ความสมบูรณ์ (Striving for Superiority) เป็นพลังขับเคลื่อนพัฒนาการของบุคคล",
  },
  {
    id: "school-aesthetics",
    title: "Aesthetics",
    slug: "aesthetics",
    thaiTitle: "สุนทรียศาสตร์ / ปรัชญาศิลปะ",
    aliases: ["Aesthetics", "ปรัชญาศิลปะ", "สุนทรียศาสตร์", "สุนทรียศาสตร์ / ปรัชญาศิลปะ"],
    nodeType: "school",
    description: "แขนงปรัชญาที่ศึกษาความงาม รสนิยม และคุณค่าของศิลปะ ว่าอะไรสวยงาม ทำไมเราจึงซาบซึ้ง และศิลปะทำหน้าที่อะไรในชีวิตมนุษย์",
  },
  {
    id: "school-ai-ethics",
    title: "AI Ethics",
    slug: "ai-ethics",
    thaiTitle: "จริยธรรมปัญญาประดิษฐ์",
    aliases: ["AI Ethics", "จริยธรรมปัญญาประดิษฐ์"],
    nodeType: "school",
    description: "แขนงจริยศาสตร์ที่ศึกษาผลกระทบทั้งดีและร้ายของ AI ต่อมนุษย์ สังคม และความยุติธรรม รวมถึงการออกแบบ AI ให้สอดคล้องกับคุณค่ามนุษย์",
  },
  {
    id: "school-analytic-philosophy",
    title: "Analytic Philosophy",
    slug: "analytic-philosophy",
    thaiTitle: "ปรัชญาวิเคราะห์ / ภาษาและตรรกวิทยา",
    aliases: ["Analytic Philosophy", "ปรัชญาวิเคราะห์", "ปรัชญาวิเคราะห์ / ภาษาและตรรกวิทยา", "ภาษาและตรรกวิทยา"],
    nodeType: "school",
    description: "ประเพณีปรัชญาที่ใช้การวิเคราะห์ภาษาและตรรกวิทยาเพื่อคลี่คลายปัญหาเชิงปรัชญา เน้นความชัดเจนและข้อสนับสนุนเชิงตรรกะ",
  },
  {
    id: "school-analytical-psychology",
    title: "Analytical Psychology",
    slug: "analytical-psychology",
    thaiTitle: "จิตวิทยาเชิงลึกแนวคาร์ล ยุง",
    aliases: ["Analytical Psychology", "Jungian Psychology", "Jungian Thinkers Reference List", "จิตวิทยาวิเคราะห์", "จิตวิทยาสายยุง", "จิตวิทยาเชิงลึกแนวคาร์ล ยุง"],
    nodeType: "school",
    description: "สำนักของ Carl Jung ที่ศึกษาจิตไร้สำนึกผ่านสัญลักษณ์ ตำนาน และ archetype เน้นกระบวนการปัจเจกภาพ (Individuation) เพื่อบูรณาการตัวตน",
  },
  {
    id: "school-animal-ethics",
    title: "Animal Ethics",
    slug: "animal-ethics",
    thaiTitle: "จริยธรรมสัตว์",
    aliases: ["Animal Ethics", "จริยธรรมสัตว์"],
    nodeType: "school",
    description: "แขนงจริยศาสตร์ที่ตั้งคำถามว่ามนุษย์มีหน้าที่ทางจริยธรรมต่อสัตว์อย่างไร ครอบคลุมสวัสดิภาพสัตว์ สิทธิสัตว์ และความยุติธรรมข้ามสายพันธุ์",
  },
  {
    id: "school-archetypal-psychology",
    title: "Archetypal Psychology",
    slug: "archetypal-psychology",
    thaiTitle: "จิตวิทยาเชิงแม่แบบ",
    aliases: ["Archetypal Psychology", "จิตวิทยาเชิงแม่แบบ"],
    nodeType: "school",
    description: "สำนักที่ขยายงานของ Jung โดยเน้นมิติเชิงกวีและจินตนาการของจิต ใช้การเล่าเรื่องและสัญลักษณ์เป็นเครื่องมือทำความเข้าใจชีวิตภายใน",
  },
  {
    id: "school-aristotelianism",
    title: "Aristotelianism",
    slug: "aristotelianism",
    thaiTitle: "ลัทธิอริสโตเติล",
    aliases: ["Aristotelianism", "ลัทธิอริสโตเติล"],
    nodeType: "school",
    description: "ประเพณีปรัชญาที่สืบทอดจากอริสโตเติล เน้นการสังเกตจากประสบการณ์จริง ตรรกวิทยา และแนวคิดเรื่องจุดประสงค์ชีวิต (Telos) และความดีงามสูงสุด (Eudaimonia)",
  },
  {
    id: "school-attachment-mentalization-developmental",
    title: "Attachment / Mentalization / Developmental",
    slug: "attachment-mentalization-developmental",
    thaiTitle: "จิตวิทยาพัฒนาการ / ความผูกพัน",
    aliases: ["Attachment / Mentalization / Developmental", "Attachment Mentalization Developmental", "ความผูกพัน", "จิตวิทยาพัฒนาการ", "จิตวิทยาพัฒนาการ / ความผูกพัน"],
    nodeType: "school",
    description: "กลุ่มสำนักที่ศึกษาความผูกพันระหว่างแม่-ลูก การพัฒนาความสามารถทางจิต (Mentalization) และผลกระทบที่มีต่อความสัมพันธ์ในวัยผู้ใหญ่",
  },
  {
    id: "school-behaviorism",
    title: "Behaviorism",
    slug: "behaviorism",
    thaiTitle: "พฤติกรรมนิยม",
    aliases: ["Behaviorism", "พฤติกรรมนิยม"],
    nodeType: "school",
    description: "สำนักที่ศึกษาพฤติกรรมที่สังเกตได้เท่านั้น ไม่สนใจจิตภายใน เน้นการเสริมแรง (Reinforcement) และการเรียนรู้ผ่านเงื่อนไข (Conditioning)",
  },
  {
    id: "school-buddhist-philosophy",
    title: "Buddhist Philosophy",
    slug: "buddhist-philosophy",
    thaiTitle: "ปรัชญาพุทธ",
    aliases: ["Buddhist Philosophy", "ปรัชญาพุทธ"],
    nodeType: "school",
    description: "ปรัชญาที่วิเคราะห์ความทุกข์ อนัตตา และการดับทุกข์ผ่านสมาธิและปัญญา ครอบคลุมนิกายเถรวาท มหายาน และวัชรยาน",
  },
  {
    id: "school-cbt",
    title: "CBT",
    slug: "cbt",
    thaiTitle: "กลุ่มพฤติกรรมบำบัดและความคิด (CBT/ACT/DBT)",
    aliases: ["CBT", "CBT/ACT/DBT", "กลุ่มพฤติกรรมบำบัดและความคิด", "กลุ่มพฤติกรรมบำบัดและความคิด (CBT/ACT/DBT)"],
    nodeType: "school",
    description: "กลุ่มบำบัดที่เน้นการเปลี่ยนแปลงความคิดและพฤติกรรมที่ไม่ช่วยเหลือ รวมถึง CBT (เปลี่ยนความคิด), ACT (ยอมรับและทำตามคุณค่า), DBT (จัดการอารมณ์รุนแรง)",
  },
  {
    id: "school-chinese-philosophy",
    title: "Chinese Philosophy",
    slug: "chinese-philosophy",
    thaiTitle: "ปรัชญาจีน",
    aliases: ["Chinese Philosophy", "ปรัชญาจีน"],
    nodeType: "school",
    description: "ประเพณีปรัชญาที่ครอบคลุมขงจื๊อ เตาซี และพุทธศาสนาจีน เน้นความกลมกลืนในสังคม ธรรมชาติ และชีวิตที่สมดุล",
  },
  {
    id: "school-christian-philosophy",
    title: "Christian Philosophy",
    slug: "christian-philosophy",
    thaiTitle: "ปรัชญาคริสต์",
    aliases: ["Christian Philosophy", "ปรัชญาคริสต์"],
    nodeType: "school",
    description: "ประเพณีปรัชญาที่ผสานความเชื่อทางศาสนาคริสต์กับตรรกวิทยา ครอบคลุมเทววิทยา จริยศาสตร์ และปรัชญาจิตวิทยาของนักบุญออกัสตินและทอมัส อไควนัส",
  },
  {
    id: "school-classical-greek",
    title: "Ancient Greek Philosophy",
    slug: "classical-greek",
    thaiTitle: "ปรัชญากรีกโบราณ / ปรัชญาคลาสสิก",
    aliases: ["Ancient Greek Philosophy", "ปรัชญากรีกโบราณ", "ปรัชญากรีกโบราณ / ปรัชญาคลาสสิก", "ปรัชญาคลาสสิก"],
    nodeType: "school",
    description: "รากฐานของปรัชญาตะวันตก จากโซเครติส เพลโต และอริสโตเติล ตั้งคำถามเรื่องความจริง ความดีงาม และความหมายของชีวิต",
  },
  {
    id: "school-critical-theory",
    title: "Critical Theory",
    slug: "critical-theory",
    thaiTitle: "ทฤษฎีวิพากษ์ (สำนักแฟรงก์เฟิร์ต)",
    aliases: ["Critical Theory", "ทฤษฎีวิพากษ์", "ทฤษฎีวิพากษ์ (สำนักแฟรงก์เฟิร์ต)", "สำนักแฟรงก์เฟิร์ต"],
    nodeType: "school",
    description: "สำนักที่วิพากษ์สังคมทุนนิยมและวัฒนธรรมมวลชน โดยผสานมาร์กซิสต์กับจิตวิเคราะห์ของฟรอยด์ เพื่อเปิดเผยอำนาจที่แฝงอยู่ในวัฒนธรรม",
  },
  {
    id: "school-cultural",
    title: "Cultural",
    slug: "cultural",
    thaiTitle: "จิตวิทยาวัฒนธรรม",
    aliases: ["Cultural", "จิตวิทยาวัฒนธรรม"],
    nodeType: "school",
    description: "สำนักที่ศึกษาอิทธิพลของวัฒนธรรมต่อพฤติกรรมและความคิดของมนุษย์ เปรียบเทียบค่านิยมและรูปแบบจิตใจข้ามสังคม",
  },
  {
    id: "school-cybernetics",
    title: "Cybernetics",
    slug: "cybernetics",
    thaiTitle: "ไซเบอร์เนติกส์ / ทฤษฎีระบบ",
    aliases: ["Cybernetics", "ทฤษฎีระบบ", "ไซเบอร์เนติกส์", "ไซเบอร์เนติกส์ / ทฤษฎีระบบ"],
    nodeType: "school",
    description: "ศาสตร์ที่ศึกษาการควบคุมและการสื่อสารในระบบ ทั้งสัตว์ เครื่องจักร และสังคม โดยใช้แนวคิดป้อนกลับ (Feedback Loop) เพื่อทำความเข้าใจพฤติกรรม",
  },
  {
    id: "school-emotion-theory",
    title: "Emotion Theory",
    slug: "emotion-theory",
    thaiTitle: "ทฤษฎีอารมณ์ความรู้สึก",
    aliases: ["Emotion Theory", "ทฤษฎีอารมณ์ความรู้สึก"],
    nodeType: "school",
    description: "แขนงจิตวิทยาที่ศึกษาธรรมชาติของอารมณ์ ทั้งที่มา กลไก และผลกระทบต่อพฤติกรรมและการตัดสินใจ ครอบคลุมทฤษฎีหลายแขนงตั้งแต่ James-Lange ถึง Appraisal Theory",
  },
  {
    id: "school-environmental-philosophy",
    title: "Environmental Philosophy",
    slug: "environmental-philosophy",
    thaiTitle: "ปรัชญาสิ่งแวดล้อม",
    aliases: ["Environmental Philosophy", "ปรัชญาสิ่งแวดล้อม"],
    nodeType: "school",
    description: "แขนงปรัชญาที่ตั้งคำถามเรื่องความสัมพันธ์ระหว่างมนุษย์กับธรรมชาติ คุณค่าของระบบนิเวศ และหน้าที่ทางจริยธรรมต่อสิ่งแวดล้อม",
  },
  {
    id: "school-epistemology",
    title: "Epistemology",
    slug: "epistemology",
    thaiTitle: "ญาณวิทยา / ทฤษฎีความรู้",
    aliases: ["Epistemology", "ญาณวิทยา", "ญาณวิทยา / ทฤษฎีความรู้", "ทฤษฎีความรู้"],
    nodeType: "school",
    description: "แขนงปรัชญาที่ศึกษาธรรมชาติของความรู้ ว่าเรารู้อะไรได้อย่างไร อะไรคือความเชื่อที่ชอบธรรม และขีดจำกัดของความรู้มนุษย์",
  },
  {
    id: "school-ethics",
    title: "Ethics",
    slug: "ethics",
    thaiTitle: "จริยศาสตร์ / ปรัชญาศีลธรรม",
    aliases: ["Ethics", "จริยศาสตร์", "จริยศาสตร์ / ปรัชญาศีลธรรม", "ปรัชญาศีลธรรม"],
    nodeType: "school",
    description: "แขนงปรัชญาที่ศึกษาความถูกต้องและหน้าที่ทางศีลธรรม ครอบคลุมจริยศาสตร์ผลลัพธ์นิยม (Utilitarianism) จริยศาสตร์หน้าที่ (Deontology) และจริยศาสตร์คุณธรรม (Virtue Ethics)",
  },
  {
    id: "school-existentialism",
    title: "Existentialism",
    slug: "existentialism",
    thaiTitle: "อัตถิภาวนิยม / อับเซิร์ดดิสม์",
    aliases: ["Existentialism", "อัตถิภาวนิยม", "อัตถิภาวนิยม / อับเซิร์ดดิสม์", "อับเซิร์ดดิสม์"],
    nodeType: "school",
    description: "สำนักที่เน้นเสรีภาพของบุคคลและความรับผิดชอบในการเลือกสร้างความหมายชีวิตด้วยตนเอง ท่ามกลางโลกที่ไม่มีความหมายสำเร็จรูป (Sartre, Camus, Kierkegaard)",
  },
  {
    id: "school-family-systems",
    title: "Family Systems",
    slug: "family-systems",
    thaiTitle: "ทฤษฎีระบบครอบครัวและการบำบัด",
    aliases: ["Family Systems", "ทฤษฎีระบบครอบครัวและการบำบัด"],
    nodeType: "school",
    description: "สำนักที่มองครอบครัวเป็นระบบหนึ่งเดียวที่มีกฎและบทบาทซ่อนเร้น ปัญหาของสมาชิกคนหนึ่งสะท้อนความผิดปกติของระบบครอบครัวทั้งหมด",
  },
  {
    id: "school-feminist-philosophy",
    title: "Feminist Philosophy",
    slug: "feminist-philosophy",
    thaiTitle: "ปรัชญาเฟมินิสต์",
    aliases: ["Feminist Philosophy", "ปรัชญาเฟมินิสต์"],
    nodeType: "school",
    description: "แขนงปรัชญาที่วิเคราะห์ความไม่เท่าเทียมทางเพศ อำนาจของปิตาธิปไตย และการปลดปล่อยสตรี ผ่านมิติเชิงสังคม การเมือง และวัฒนธรรม",
  },
  {
    id: "school-hellenistic-philosophy",
    title: "Hellenistic Philosophy",
    slug: "hellenistic-philosophy",
    thaiTitle: "ปรัชญาเฮลเลนิสติก",
    aliases: ["Hellenistic Philosophy", "ปรัชญาเฮลเลนิสติก"],
    nodeType: "school",
    description: "กลุ่มปรัชญาหลังอเล็กซานเดอร์มหาราช ได้แก่ สโตอิก อpicurean และ Skeptic เน้นการค้นหาความสงบใจ (Ataraxia) และชีวิตที่สมดุล",
  },
  {
    id: "school-hermeneutics",
    title: "Hermeneutics",
    slug: "hermeneutics",
    thaiTitle: "ศาสตร์แห่งการตีความ",
    aliases: ["Hermeneutics", "ศาสตร์แห่งการตีความ"],
    nodeType: "school",
    description: "ศาสตร์ที่ศึกษาวิธีการตีความข้อความ ศิลปะ และเหตุการณ์ เน้นว่าผู้ตีความย่อมมีบริบทของตนเองที่ส่งผลต่อความเข้าใจ (Gadamer, Heidegger)",
  },
  {
    id: "school-humanistic-psychology",
    title: "Humanistic Psychology",
    slug: "humanistic-psychology",
    thaiTitle: "จิตวิทยามนุษยนิยม",
    aliases: ["Humanistic Psychology", "จิตวิทยามนุษยนิยม"],
    nodeType: "school",
    description: "สำนักที่เน้นศักยภาพในการเติบโตของมนุษย์(Self-Actualization) มองมนุษย์ในฐานะผู้เลือกสร้างชะตากรรมตนเอง ไม่ใช่เหยื่อของสิ่งแวดล้อมหรือจิตไร้สำนึก (Rogers, Maslow)",
  },
  {
    id: "school-ifs",
    title: "IFS",
    slug: "ifs",
    thaiTitle: "จิตบำบัดระบบครอบครัวภายใน (IFS)",
    aliases: ["IFS", "จิตบำบัดระบบครอบครัวภายใน", "จิตบำบัดระบบครอบครัวภายใน (IFS)"],
    nodeType: "school",
    description: "สำนักบำบัดที่มองจิตใจเป็นระบบครอบครัวภายใน มีส่วนต่าง ๆ (Parts) ที่มีบทบาทและอารมณ์ของตนเอง และมี Self 作为ศูนย์กลางการรักษา",
  },
  {
    id: "school-indian-philosophy",
    title: "Indian Philosophy",
    slug: "indian-philosophy",
    thaiTitle: "ปรัชญาอินเดีย",
    aliases: ["Indian Philosophy", "ปรัชญาอินเดีย"],
    nodeType: "school",
    description: "ประเพณีปรัชญาที่ครอบคลุมเวดานตะ ยุค สรีมสคญา และพุทธศาสนา ตั้งคำถามเรื่องอัตลักษณ์ ความจริงสูงสุด และการหลุดพ้นจากวัฏจักร",
  },
  {
    id: "school-indigenous-philosophy",
    title: "Indigenous Philosophy",
    slug: "indigenous-philosophy",
    thaiTitle: "ปรัชญาชนเผ่าพื้นเมือง",
    aliases: ["Indigenous Philosophy", "ปรัชญาชนเผ่าพื้นเมือง"],
    nodeType: "school",
    description: "ประเพณีปรัชญาของชนเผ่าพื้นเมืองทั่วโลก เน้นความเชื่อมโยงระหว่างมนุษย์กับธรรมชาติ จิตวิญญาณ และชุมชน มากกว่าตรรกวิทยาแบบตะวันตก",
  },
  {
    id: "school-islamic-philosophy",
    title: "Islamic Philosophy",
    slug: "islamic-philosophy",
    thaiTitle: "ปรัชญาอิสลาม",
    aliases: ["Islamic Philosophy", "ปรัชญาอิสลาม"],
    nodeType: "school",
    description: "ประเพณีปรัชญาที่ผสานอัลกุรอานกับปรัชญากรีก ครอบคลุมอัลกินดี อิบนซินา และอิbnรัชดี เน้นความสัมพันธ์ระหว่างเหตุผลกับศรัทธา",
  },
  {
    id: "school-jewish-philosophy",
    title: "Jewish Philosophy",
    slug: "jewish-philosophy",
    thaiTitle: "ปรัชญายิว",
    aliases: ["Jewish Philosophy", "ปรัชญายิว"],
    nodeType: "school",
    description: "ประเพณีปรัชญาที่ตีความ Torah และ Rabbinic Literature ผ่านตรรกวิทยา ครอบคลุมไมมอนิดีส สปโนซา และปรัชญาโมเดิร์นยิว",
  },
  {
    id: "school-lacanian-psychoanalysis-thinkers-reference-list",
    title: "Lacanian Psychoanalysis",
    slug: "lacanian-psychoanalysis-thinkers-reference-list",
    thaiTitle: "จิตวิเคราะห์แนวลากอง",
    aliases: ["Lacanian Psychoanalysis", "Lacanian", "Lacanian Psychoanalysis Thinkers Reference List", "จิตวิเคราะห์แนวลากอง"],
    nodeType: "school",
    description: "สำนักจิตวิเคราะห์ของ Jacques Lacan ที่ผสานฟรอยด์กับภาษาศาสตร์และปรัชญา เน้นว่าจิตสำนึกถูกจัดรูปด้วยภาษา (The unconscious is structured like a language)",
  },
  {
    id: "school-metaphysics",
    title: "Metaphysics",
    slug: "metaphysics",
    thaiTitle: "อภิปรัชญา",
    aliases: ["Metaphysics", "อภิปรัชญา"],
    nodeType: "school",
    description: "แขนงปรัชญาที่ศึกษาธรรมชาติสูงสุดของความเป็นจริง ครอบคลุมontology (ธรรมชาติของสิ่งมีอยู่) และ cosmology (ธรรมชาติของ宇宙)",
  },
  {
    id: "school-narrative-psychology",
    title: "Narrative Psychology",
    slug: "narrative-psychology",
    thaiTitle: "จิตวิทยาเชิงเล่าเรื่อง",
    aliases: ["Narrative Psychology", "จิตวิทยาเชิงเล่าเรื่อง"],
    nodeType: "school",
    description: "สำนักที่มองว่ามนุษย์สร้างความเข้าใจตนเองผ่านการเล่าเรื่อง (Life Story) เนื้อหาในชีวิตไม่ได้มีความหมายในตัวเอง แต่ได้ความหมายจากการเรียบเรียง",
  },
  {
    id: "school-neuroscience",
    title: "Neuroscience",
    slug: "neuroscience",
    thaiTitle: "ประสาทวิทยาศาสตร์ / ประสาทจิตวิเคราะห์",
    aliases: ["Neuroscience", "ประสาทจิตวิเคราะห์", "ประสาทวิทยาศาสตร์", "ประสาทวิทยาศาสตร์ / ประสาทจิตวิเคราะห์"],
    nodeType: "school",
    description: "ศาสตร์ที่ศึกษาการทำงานของสมองและระบบประสาท เพื่ออธิบายพฤติกรรม ความคิด และอารมณ์ในเชิงชีวภาพ ครอบคลุม cognitive neuroscience และ neuropsychoanalysis",
  },
  {
    id: "school-object-relations",
    title: "Object Relations",
    slug: "object-relations",
    thaiTitle: "ทฤษฎีความสัมพันธ์เชิงวัตถุ",
    aliases: ["Object Relations", "ทฤษฎีความสัมพันธ์เชิงวัตถุ"],
    nodeType: "school",
    description: "สำนักจิตวิทยาเชิงลึกที่เน้นว่าความสัมพันธ์ระหว่างแม่-ลูกในวัยเด็กเป็นตัวกำหนดรูปแบบความสัมพันธ์ในวัยผู้ใหญ่ (Klein, Winnicott, Fairbairn)",
  },
  {
    id: "school-personality-psychology",
    title: "Personality Psychology",
    slug: "personality-psychology",
    thaiTitle: "จิตวิทยาบุคลิกภาพ",
    aliases: ["Personality Psychology", "จิตวิทยาบุคลิกภาพ"],
    nodeType: "school",
    description: "แขนงจิตวิทยาที่ศึกษาแบบแผนพฤติกรรมและความคิดที่สม่ำเสมอของบุคคล ครอบคลุมทฤษฎี Big Five, MBTI และทฤษฎีบุคลิกภาพเชิงลึก",
  },
  {
    id: "school-phenomenology",
    title: "Phenomenology",
    slug: "phenomenology",
    thaiTitle: "ปรากฏการณ์วิทยา",
    aliases: ["Phenomenology", "ปรากฏการณ์วิทยา"],
    nodeType: "school",
    description: "แขนงปรัชญาที่ศึกษาประสบการณ์ตรงของจิตใจ โดยละวางสมมติฐานเกี่ยวกับโลกภายนอกเพื่อทำความเข้าใจปรากฏการณ์ในมิติที่มันปรากฏต่อจิตสำนึก (Husserl, Heidegger)",
  },
  {
    id: "school-phenomenology-of-psyche",
    title: "Phenomenology of Psyche",
    slug: "phenomenology-of-psyche",
    thaiTitle: "ปรากฏการณ์วิทยาแห่งจิต",
    aliases: ["Phenomenology of Psyche", "Phenomenology Of psyche", "ปรากฏการณ์วิทยาแห่งจิต"],
    nodeType: "school",
    description: "แขนงที่ผสานปรากฏการณ์วิทยากับจิตวิทยาเชิงลึก เพื่อทำความเข้าใจจิตใจในมิติที่มันปรากฏต่อตนเอง ไม่ใช่แค่พฤติกรรมภายนอก",
  },
  {
    id: "school-philosophy-of-language",
    title: "Philosophy of Language",
    slug: "philosophy-of-language",
    thaiTitle: "ปรัชญาภาษา",
    aliases: ["Philosophy of Language", "ปรัชญาภาษา"],
    nodeType: "school",
    description: "แขนงปรัชญาที่ศึกษาความสัมพันธ์ระหว่างภาษา ความคิด และความเป็นจริง ตั้งคำถามว่าภาษาทำหน้าที่อะไรและมีขอบเขตอย่างไร (Wittgenstein, Austin, Derrida)",
  },
  {
    id: "school-philosophy-of-mind",
    title: "Philosophy of Mind",
    slug: "philosophy-of-mind",
    thaiTitle: "ปรัชญาแห่งจิต",
    aliases: ["Philosophy of Mind", "ปรัชญาแห่งจิต"],
    nodeType: "school",
    description: "แขนงปรัชญาที่ตั้งคำถามว่าจิตใจคืออะไร สัมพันธ์กับร่างกายอย่างไร ครอบคลุมปัญหาจิต-กาย (Mind-Body Problem) และจิตสำนึก (Consciousness)",
  },
  {
    id: "school-philosophy-of-race",
    title: "Philosophy of Race",
    slug: "philosophy-of-race",
    thaiTitle: "ปรัชญาเรื่องชาติพันธุ์",
    aliases: ["Philosophy of Race", "ปรัชญาเรื่องชาติพันธุ์"],
    nodeType: "school",
    description: "แขนงปรัชญาที่วิเคราะห์แนวคิดเรื่องเชื้อชาติ การเหยียดผิว และอัตลักษณ์ทางเชื้อชาติว่าเป็นสิ่งก่อสร้างทางสังคม (Social Construction) หรือมีรากฐานทางชีวภาพ",
  },
  {
    id: "school-philosophy-of-religion",
    title: "Philosophy of Religion",
    slug: "philosophy-of-religion",
    thaiTitle: "ปรัชญาศาสนา",
    aliases: ["Philosophy of Religion", "ปรัชญาศาสนา"],
    nodeType: "school",
    description: "แขนงปรัชญาที่วิเคราะห์ความเชื่อทางศาสนาด้วยตรรกวิทยา ตั้งคำถามเรื่องการดำรงอยู่ของพระเจ้า ความชั่วร้าย และความสัมพันธ์ระหว่างศรัทธากับเหตุผล",
  },
  {
    id: "school-philosophy-of-science",
    title: "Philosophy of Science",
    slug: "philosophy-of-science",
    thaiTitle: "ปรัชญาวิทยาศาสตร์",
    aliases: ["Philosophy of Science", "ปรัชญาวิทยาศาสตร์"],
    nodeType: "school",
    description: "แขนงปรัชญาที่ศึกษาวิธีการและขอบเขตของวิทยาศาสตร์ ตั้งคำถามว่าอะไรนับเป็นวิทยาศาสตร์ อะไรคือการยืนยัน และทฤษฎีวิทยาศาสตร์เปลี่ยนแปลงอย่างไร (Kuhn, Popper, Lakatos)",
  },
  {
    id: "school-philosophy-of-technology",
    title: "Philosophy of Technology",
    slug: "philosophy-of-technology",
    thaiTitle: "ปรัชญาเทคโนโลยี",
    aliases: ["Philosophy of Technology", "ปรัชญาเทคโนโลยี"],
    nodeType: "school",
    description: "แขนงปรัชญาที่วิเคราะห์ความสัมพันธ์ระหว่างมนุษย์กับเทคโนโลยี ตั้งคำถามว่าเทคโนโลยีเปลี่ยนแปลงชีวิต จริยธรรม และตัวตนของเราอย่างไร (Heidegger, Ellul, Feenberg)",
  },
  {
    id: "school-platonism",
    title: "Platonism",
    slug: "platonism",
    thaiTitle: "ลัทธิเพลโต",
    aliases: ["Platonism", "ลัทธิเพลโต"],
    nodeType: "school",
    description: "ประเพณีปรัชญาที่สืบทอดจากเพลโต เน้นว่ามีโลกแห่งแบบ (Forms) ที่สมบูรณ์แบบและเป็นนิรันดร์ ซึ่งโลกแห่งประสาทสัมผัสเป็นเพียงเงาของโลกนั้น",
  },
  {
    id: "school-political-philosophy",
    title: "Political Philosophy",
    slug: "political-philosophy",
    thaiTitle: "ปรัชญาการเมือง",
    aliases: ["Political Philosophy", "ปรัชญาการเมือง"],
    nodeType: "school",
    description: "แขนงปรัชญาที่วิเคราะห์รัฐ อำนาจ ความยุติธรรม และสิทธิเสรีภาพ ตั้งคำถามว่าอะไรคือสังคมที่ดีและเราควรมีชีวิตร่วมกันอย่างไร (Rawls, Nozick, Marx)",
  },
  {
    id: "school-positivism",
    title: "Positivism",
    slug: "positivism",
    thaiTitle: "ปฏิฐานนิยม",
    aliases: ["Positivism", "ปฏิฐานนิยม"],
    nodeType: "school",
    description: "สำนักที่ยืนยันว่าความรู้ที่ถูกต้องต้องมาจากการสังเกตและพิสูจน์ได้เท่านั้น ปฏิเสธปรัชญาเชิงอภิปรัชญาที่พิสูจน์ไม่ได้ (Comte, Vienna Circle)",
  },
  {
    id: "school-postcolonial-philosophy",
    title: "Postcolonial Philosophy",
    slug: "postcolonial-philosophy",
    thaiTitle: "ปรัชญาหลังอาณานิคม",
    aliases: ["Postcolonial Philosophy", "ปรัชญาหลังอาณานิคม"],
    nodeType: "school",
    description: "แขนงปรัชญาที่วิพากษ์ผลกระทบทางวัฒนธรรมและการเมืองของการล่าอาณานิคม เปิดเผยอคติในความรู้แบบตะวันตกและเรียกร้องสิทธิในการเล่าเรื่องของตนเอง (Said, Spivak, Bhabha)",
  },
  {
    id: "school-posthumanism",
    title: "Posthumanism",
    slug: "posthumanism",
    thaiTitle: "แนวคิดหลังมนุษยนิยม",
    aliases: ["Posthumanism", "แนวคิดหลังมนุษยนิยม"],
    nodeType: "school",
    description: "แขนงปรัชญาที่ท้าทายแนวคิดเรื่องมนุษย์เป็นศูนย์กลาง (Humanism) ตั้งคำถามว่าเทคโนโลยีชีวภาพและ AI กำลังเปลี่ยนนิยามของความเป็นมนุษย์อย่างไร",
  },
  {
    id: "school-pragmatism",
    title: "Pragmatism",
    slug: "pragmatism",
    thaiTitle: "ปฏิบัตินิยม",
    aliases: ["Pragmatism", "ปฏิบัตินิยม"],
    nodeType: "school",
    description: "ประเพณีปรัชญาอเมริกันที่ตัดสินความจริงจากผลลัพธ์ในทางปฏิบัติ ไม่ใช่ตรรกวิทยาล้วน ความคิดมีค่าก็ต่อเมื่อมันช่วยให้เราใช้ชีวิตได้ดีขึ้น (James, Dewey, Peirce)",
  },
  {
    id: "school-process-philosophy",
    title: "Process Philosophy",
    slug: "process-philosophy",
    thaiTitle: "ปรัชญากระบวนการ",
    aliases: ["Process Philosophy", "ปรัชญากระบวนการ"],
    nodeType: "school",
    description: "ปรัชญาของ Alfred North Whitehead ที่มองว่าความเป็นจริงไม่ใช่สิ่งตายตัว แต่เป็นกระบวนการเปลี่ยนแปลงอยู่ตลอดเวลา ทุกสิ่งล้วนเชื่อมโยงกัน",
  },
  {
    id: "school-psychoanalysis",
    title: "Psychoanalysis",
    slug: "psychoanalysis",
    thaiTitle: "จิตวิเคราะห์แนวฟรอยด์",
    aliases: ["Psychoanalysis", "Freudian", "จิตวิเคราะห์", "จิตวิเคราะห์แนวฟรอยด์"],
    nodeType: "school",
    description: "สำนักของ Sigmund Freud ที่วิเคราะห์จิตผ่านความฝัน การแปลความ และแรงขับทางเพศ (Libido) เน้นความขัดแย้งระหว่าง Id, Ego และ Superego",
  },
  {
    id: "school-psychology-of-religion",
    title: "Psychology of Religion",
    slug: "psychology-of-religion",
    thaiTitle: "จิตวิทยาศาสนา",
    aliases: ["Psychology of Religion", "จิตวิทยาศาสนา"],
    nodeType: "school",
    description: "แขนงจิตวิทยาที่ศึกษาประสบการณ์ทางศาสนาในมิติทางจิต ครอบคลุมความเชื่อ การสวดมนต์ นิมิต และผลกระทบต่อสุขภาพจิต (James, Jung, Maslow)",
  },
  {
    id: "school-queer-theory",
    title: "Queer Theory",
    slug: "queer-theory",
    thaiTitle: "ทฤษฎีเควียร์ / เพศสภาพศึกษา",
    aliases: ["Queer Theory", "ทฤษฎีเควียร์", "ทฤษฎีเควียร์ / เพศสภาพศึกษา", "เพศสภาพศึกษา"],
    nodeType: "school",
    description: "แขนงทฤษฎีวิพากษ์ที่ตั้งคำถามกับเพศวิถีและอัตลักษณ์ทางเพศที่ถูกสังคมกำหนด เปิดพื้นที่ให้กับประสบการณ์ที่อยู่นอกระบบ binary (Butler, Sedgwick)",
  },
  {
    id: "school-social-psychology",
    title: "Social Psychology",
    slug: "social-psychology",
    thaiTitle: "จิตวิทยาสังคม",
    aliases: ["Social Psychology", "จิตวิทยาสังคม"],
    nodeType: "school",
    description: "แขนงจิตวิทยาที่ศึกษาอิทธิพลของสังคมต่อพฤติกรรมและความคิดของบุคคล ครอบคลุมการเชื่อฟัง (Obedience), การหมู่ (Conformity) และอคติทางสังคม",
  },
  {
    id: "school-structuralism",
    title: "Structuralism",
    slug: "structuralism",
    thaiTitle: "โครงสร้างนิยม / หลังโครงสร้างนิยม",
    aliases: ["Structuralism", "หลังโครงสร้างนิยม", "โครงสร้างนิยม", "โครงสร้างนิยม / หลังโครงสร้างนิยม"],
    nodeType: "school",
    description: "กลุ่มสำนักที่วิเคราะห์โครงสร้างซ่อนเร้นเบื้องหลังวัฒนธรรมและภาษา (Lévi-Strauss, Saussure) ต่อมาแตกเป็นหลังโครงสร้างนิยมที่ตั้งคำถามกับความหมายที่ตายตัว (Derrida, Foucault)",
  },
  {
    id: "school-transpersonal",
    title: "Transpersonal",
    slug: "transpersonal",
    thaiTitle: "จิตวิทยาข้ามบุคคล",
    aliases: ["Transpersonal", "จิตวิทยาข้ามบุคคล"],
    nodeType: "school",
    description: "สำนักที่ขยายขอบเขตจิตวิทยาให้รวมถึงประสบการณ์ทางจิตวิญญาณ การตระหนักรู้ข้ามตัวตน และสภาวะจิตที่อยู่เหนืออัตตา (Maslow, Wilber, Grof)",
  },
  {
    id: "school-trauma-somatic-dissociation",
    title: "Trauma / Somatic / Dissociation",
    slug: "trauma-somatic-dissociation",
    thaiTitle: "จิตวิทยาบาดแผลทางใจและกายสัมผัส",
    aliases: ["Trauma / Somatic / Dissociation", "Trauma Somatic Dissociation", "จิตวิทยาบาดแผลทางใจและกายสัมผัส"],
    nodeType: "school",
    description: "กลุ่มสำนักที่ศึกษาบาดแผลทางใจ (Trauma) ในมิติของร่างกายและการแยกตัว (Dissociation) เน้นการบำบัดผ่านร่างกาย (Somatic Experiencing) ไม่ใช่แค่การพูดคุย",
  },
];

export const conceptRegistry: ConceptRegistryItem[] = [
  {
    id: "concept-psyche",
    title: "Psyche",
    slug: "psyche",
    thaiTitle: "ไซคี",
    aliases: ["Psyche", "ไซคี", "psukhe"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "ชื่อเรียกพื้นที่ทั้งหมดของชีวิตภายใน ทั้งส่วนที่เรารู้ตัวและส่วนที่ยังทำงานอยู่ใต้ระดับการรู้ตัว ไม่จำกัดอยู่เฉพาะความคิดหรืออารมณ์",
  },
  {
    id: "concept-ego",
    title: "Ego",
    slug: "ego",
    thaiTitle: "อัตตา",
    aliases: ["Ego", "อัตตา"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "จุดที่เรารู้สึกว่าเป็น ฉัน เป็นผู้ตัดสินใจและจดจำในแต่ละวัน แต่เป็นเพียงส่วนหนึ่งของชีวิตภายใน ไม่ใช่ทั้งหมด",
  },
  {
    id: "concept-shadow",
    title: "Shadow",
    slug: "shadow",
    thaiTitle: "เงา",
    aliases: ["Shadow", "เงา", "Jungian Shadow"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "ส่วนที่เราไม่อยากเห็นในตัวเอง มักปรากฏผ่านการตัดสินผู้อื่นอย่างรุนแรงโดยไม่รู้ตัว เป็นส่วนที่ถูกผลักออกจากระบบจิตสำนึก",
  },
  {
    id: "concept-persona",
    title: "Persona",
    slug: "persona",
    thaiTitle: "หน้ากากทางสังคม",
    aliases: ["Persona", "หน้ากากทางสังคม"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "หน้ากากที่เราสวมเมื่ออยู่ในบทบาทต่าง ๆ เช่น ที่ทำงานหรือในครอบครัว มีประโยชน์ในการเข้าสังคมแต่ไม่ใช่ตัวตนทั้งหมด",
  },
  {
    id: "concept-self",
    title: "Self",
    slug: "self",
    thaiTitle: "ตัวตนทั้งหมด",
    aliases: ["Self", "ตัวตนทั้งหมด", "Selbst"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "ศูนย์กลางและองค์รวมของชีวิตทางจิตทั้งหมด ทั้งที่รู้ตัวและไม่รู้ตัว ใหญ่กว่า Ego และเป็นเป้าหมายของกระบวนการปัจเจกภาพ",
  },
  {
    id: "concept-unconscious",
    title: "Unconscious",
    slug: "unconscious",
    thaiTitle: "จิตไร้สำนึก",
    aliases: ["Unconscious", "จิตไร้สำนึก"],
    nodeType: "concept",
    description: "พื้นที่ของจิตที่อยู่นอกการรู้ตัว แต่มีอิทธิพลต่อความคิด อารมณ์ และพฤติกรรมของเราอยู่ตลอดเวลา",
  },
  {
    id: "concept-collective-unconscious",
    title: "Collective Unconscious",
    slug: "collective-unconscious",
    thaiTitle: "จิตไร้สำนึกร่วม",
    aliases: ["Collective Unconscious", "จิตไร้สำนึกร่วม"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "ชั้นของจิตไร้สำนึกที่มนุษย์ทุกคนมีร่วมกัน เก็บแบบแผนและสัญลักษณ์สากลที่สืบทอดมาจากรุ่นสู่รุ่น",
  },
  {
    id: "concept-individuation",
    title: "Individuation",
    slug: "individuation",
    thaiTitle: "กระบวนการปัจเจกภาพ",
    aliases: ["Individuation", "กระบวนการปัจเจกภาพ"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "กระบวนการที่ค่อย ๆ รับรู้และจัดความสัมพันธ์ระหว่างส่วนต่าง ๆ ของชีวิตภายในอย่างซื่อตรง ไม่ใช่การพัฒนาตัวเองให้สมบูรณ์แบบ",
  },
  {
    id: "concept-archetype",
    title: "Archetype",
    slug: "archetype",
    thaiTitle: "แบบฉบับดั้งเดิม",
    aliases: ["Archetype", "แบบฉบับดั้งเดิม"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "แบบแผนร่วมที่ปรากฏซ้ำในจิตไร้สำนึก ความฝัน และตำนานของมนุษยชาติ เช่น แม่ วีรบุรุษ หรือเงา ไม่ใช่ภาพสำเร็จรูปแต่เป็นแนวโน้มที่จัดรูปประสบการณ์",
  },
  {
    id: "term-libido",
    title: "Libido",
    slug: "libido",
    thaiTitle: "ลิบิโด",
    aliases: ["Libido", "ลิบิโด"],
    nodeType: "term",
    description: "พลังงานทางจิต ฟรอยด์หมายถึงแรงขับทางเพศ แต่ยุงขยายเป็นพลังงานสร้างสรรค์กว้างกว่า",
  },
  {
    id: "person-carl-jung",
    title: "Carl Jung",
    slug: "carl-jung",
    thaiTitle: "คาร์ล ยุง",
    aliases: ["Carl Jung", "C. G. Jung", "Jung", "ยุง", "คาร์ล ยุง"],
    nodeType: "person",
    framework: "Analytical Psychology",
    description: "นักจิตวิทยาชาวสวิสผู้พัฒนาแนวคิด Shadow, Archetype, Individuation และจิตวิทยาวิเคราะห์ (Analytical Psychology) ซึ่งขยายขอบเขตจิตไร้สำนึกให้กว้างกว่าแรงขับทางเพศ",
  },
  {
    id: "person-sigmund-freud",
    title: "Sigmund Freud",
    slug: "sigmund-freud",
    thaiTitle: "ซิกมุนด์ ฟรอยด์",
    aliases: ["Sigmund Freud", "Freud", "ฟรอยด์"],
    nodeType: "person",
    framework: "Psychoanalysis",
    description: "แพทย์ชาวออสเตรียผู้วางรากฐานจิตวิเคราะห์ คิดค้นแนวคิด Id, Ego, Superego และเน้นบทบาทของแรงขับทางเพศในฐานะพลังขับเคลื่อนจิตใจ",
  },
  {
    id: "book-psychological-types",
    title: "Psychological Types",
    slug: "psychological-types",
    aliases: ["Psychological Types"],
    nodeType: "book",
    framework: "Analytical Psychology",
    description: "งานเขียนสำคัญของ Carl Jung ที่วางแนวคิดประเภททางจิตวิทยา (Thinking, Feeling, Sensation, Intuition) และทิศทางจิต (Introversion/Extraversion) ซึ่งเป็นรากฐานของ MBTI",
  },
  ...schoolRegistry,
];

export function getConceptBySlug(slug: string): ConceptRegistryItem | undefined {
  return conceptRegistry.find((c) => c.slug === slug);
}

// resolve โดยลำดับ: slug → title → thaiTitle → alias (กันสร้าง node ซ้ำ)
export function resolveConcept(input: string): ConceptRegistryItem | undefined {
  const q = input.trim().toLowerCase();
  return (
    conceptRegistry.find((c) => c.slug.toLowerCase() === q) ||
    conceptRegistry.find((c) => c.title.toLowerCase() === q) ||
    conceptRegistry.find((c) => (c.thaiTitle ?? "").toLowerCase() === q) ||
    conceptRegistry.find((c) => c.aliases.some((a) => a.toLowerCase() === q))
  );
}

export function conceptTitle(slug: string): string {
  return getConceptBySlug(slug)?.title ?? slug;
}
