// Concept Registry (Phase 7) — ฐานกลางของแนวคิด/นักคิด/หนังสือ/สำนัก/สัญลักษณ์/คำศัพท์
// ใช้เป็นฐานของ related concepts, backlinks, internal link suggestions และ Constellation Map

export type NodeType =
  | "concept"
  | "person"
  | "book"
  | "school"
  | "symbol"
  | "term";

export type ConceptRegistryItem = {
  id: string;
  title: string;
  slug: string;
  thaiTitle?: string;
  aliases: string[];
  nodeType: NodeType;
  framework?: string;
  description?: string;
};

// สำนักคิดทั้งหมด (school nodes) — auto-generated ให้ตรงกับ entries (content_type=school) ใน Supabase
const schoolRegistry: ConceptRegistryItem[] = [
  {
    id: "school-adlerian",
    title: "Adlerian",
    slug: "adlerian",
    thaiTitle: "จิตวิทยาแอดเลอร์ / จิตวิทยาปัจเจกบุคคล",
    aliases: ["Adlerian", "จิตวิทยาปัจเจกบุคคล", "จิตวิทยาแอดเลอร์", "จิตวิทยาแอดเลอร์ / จิตวิทยาปัจเจกบุคคล"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จิตวิทยาแอดเลอร์ / จิตวิทยาปัจเจกบุคคล",
  },
  {
    id: "school-aesthetics",
    title: "Aesthetics",
    slug: "aesthetics",
    thaiTitle: "สุนทรียศาสตร์ / ปรัชญาศิลปะ",
    aliases: ["Aesthetics", "ปรัชญาศิลปะ", "สุนทรียศาสตร์", "สุนทรียศาสตร์ / ปรัชญาศิลปะ"],
    nodeType: "school",
    description: "สำนักคิด/สาย: สุนทรียศาสตร์ / ปรัชญาศิลปะ",
  },
  {
    id: "school-ai-ethics",
    title: "AI Ethics",
    slug: "ai-ethics",
    thaiTitle: "จริยธรรมปัญญาประดิษฐ์",
    aliases: ["AI Ethics", "จริยธรรมปัญญาประดิษฐ์"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จริยธรรมปัญญาประดิษฐ์",
  },
  {
    id: "school-analytic-philosophy",
    title: "Analytic Philosophy",
    slug: "analytic-philosophy",
    thaiTitle: "ปรัชญาวิเคราะห์ / ภาษาและตรรกวิทยา",
    aliases: ["Analytic Philosophy", "ปรัชญาวิเคราะห์", "ปรัชญาวิเคราะห์ / ภาษาและตรรกวิทยา", "ภาษาและตรรกวิทยา"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาวิเคราะห์ / ภาษาและตรรกวิทยา",
  },
  {
    id: "school-analytical-psychology",
    title: "Analytical Psychology",
    slug: "analytical-psychology",
    thaiTitle: "จิตวิทยาเชิงลึกแนวคาร์ล ยุง",
    aliases: ["Analytical Psychology", "Jungian Psychology", "Jungian Thinkers Reference List", "จิตวิทยาวิเคราะห์", "จิตวิทยาสายยุง", "จิตวิทยาเชิงลึกแนวคาร์ล ยุง"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จิตวิทยาเชิงลึกแนวคาร์ล ยุง",
  },
  {
    id: "school-animal-ethics",
    title: "Animal Ethics",
    slug: "animal-ethics",
    thaiTitle: "จริยธรรมสัตว์",
    aliases: ["Animal Ethics", "จริยธรรมสัตว์"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จริยธรรมสัตว์",
  },
  {
    id: "school-archetypal-psychology",
    title: "Archetypal Psychology",
    slug: "archetypal-psychology",
    thaiTitle: "จิตวิทยาเชิงแม่แบบ",
    aliases: ["Archetypal Psychology", "จิตวิทยาเชิงแม่แบบ"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จิตวิทยาเชิงแม่แบบ",
  },
  {
    id: "school-aristotelianism",
    title: "Aristotelianism",
    slug: "aristotelianism",
    thaiTitle: "ลัทธิอริสโตเติล",
    aliases: ["Aristotelianism", "ลัทธิอริสโตเติล"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ลัทธิอริสโตเติล",
  },
  {
    id: "school-attachment-mentalization-developmental",
    title: "Attachment / Mentalization / Developmental",
    slug: "attachment-mentalization-developmental",
    thaiTitle: "จิตวิทยาพัฒนาการ / ความผูกพัน",
    aliases: ["Attachment / Mentalization / Developmental", "Attachment Mentalization Developmental", "ความผูกพัน", "จิตวิทยาพัฒนาการ", "จิตวิทยาพัฒนาการ / ความผูกพัน"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จิตวิทยาพัฒนาการ / ความผูกพัน",
  },
  {
    id: "school-behaviorism",
    title: "Behaviorism",
    slug: "behaviorism",
    thaiTitle: "พฤติกรรมนิยม",
    aliases: ["Behaviorism", "พฤติกรรมนิยม"],
    nodeType: "school",
    description: "สำนักคิด/สาย: พฤติกรรมนิยม",
  },
  {
    id: "school-buddhist-philosophy",
    title: "Buddhist Philosophy",
    slug: "buddhist-philosophy",
    thaiTitle: "ปรัชญาพุทธ",
    aliases: ["Buddhist Philosophy", "ปรัชญาพุทธ"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาพุทธ",
  },
  {
    id: "school-cbt",
    title: "CBT",
    slug: "cbt",
    thaiTitle: "กลุ่มพฤติกรรมบำบัดและความคิด (CBT/ACT/DBT)",
    aliases: ["CBT", "CBT/ACT/DBT", "กลุ่มพฤติกรรมบำบัดและความคิด", "กลุ่มพฤติกรรมบำบัดและความคิด (CBT/ACT/DBT)"],
    nodeType: "school",
    description: "สำนักคิด/สาย: กลุ่มพฤติกรรมบำบัดและความคิด (CBT/ACT/DBT)",
  },
  {
    id: "school-chinese-philosophy",
    title: "Chinese Philosophy",
    slug: "chinese-philosophy",
    thaiTitle: "ปรัชญาจีน",
    aliases: ["Chinese Philosophy", "ปรัชญาจีน"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาจีน",
  },
  {
    id: "school-christian-philosophy",
    title: "Christian Philosophy",
    slug: "christian-philosophy",
    thaiTitle: "ปรัชญาคริสต์",
    aliases: ["Christian Philosophy", "ปรัชญาคริสต์"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาคริสต์",
  },
  {
    id: "school-classical-greek",
    title: "Ancient Greek Philosophy",
    slug: "classical-greek",
    thaiTitle: "ปรัชญากรีกโบราณ / ปรัชญาคลาสสิก",
    aliases: ["Ancient Greek Philosophy", "ปรัชญากรีกโบราณ", "ปรัชญากรีกโบราณ / ปรัชญาคลาสสิก", "ปรัชญาคลาสสิก"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญากรีกโบราณ / ปรัชญาคลาสสิก",
  },
  {
    id: "school-critical-theory",
    title: "Critical Theory",
    slug: "critical-theory",
    thaiTitle: "ทฤษฎีวิพากษ์ (สำนักแฟรงก์เฟิร์ต)",
    aliases: ["Critical Theory", "ทฤษฎีวิพากษ์", "ทฤษฎีวิพากษ์ (สำนักแฟรงก์เฟิร์ต)", "สำนักแฟรงก์เฟิร์ต"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ทฤษฎีวิพากษ์ (สำนักแฟรงก์เฟิร์ต)",
  },
  {
    id: "school-cultural",
    title: "Cultural",
    slug: "cultural",
    thaiTitle: "จิตวิทยาวัฒนธรรม",
    aliases: ["Cultural", "จิตวิทยาวัฒนธรรม"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จิตวิทยาวัฒนธรรม",
  },
  {
    id: "school-cybernetics",
    title: "Cybernetics",
    slug: "cybernetics",
    thaiTitle: "ไซเบอร์เนติกส์ / ทฤษฎีระบบ",
    aliases: ["Cybernetics", "ทฤษฎีระบบ", "ไซเบอร์เนติกส์", "ไซเบอร์เนติกส์ / ทฤษฎีระบบ"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ไซเบอร์เนติกส์ / ทฤษฎีระบบ",
  },
  {
    id: "school-emotion-theory",
    title: "Emotion Theory",
    slug: "emotion-theory",
    thaiTitle: "ทฤษฎีอารมณ์ความรู้สึก",
    aliases: ["Emotion Theory", "ทฤษฎีอารมณ์ความรู้สึก"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ทฤษฎีอารมณ์ความรู้สึก",
  },
  {
    id: "school-environmental-philosophy",
    title: "Environmental Philosophy",
    slug: "environmental-philosophy",
    thaiTitle: "ปรัชญาสิ่งแวดล้อม",
    aliases: ["Environmental Philosophy", "ปรัชญาสิ่งแวดล้อม"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาสิ่งแวดล้อม",
  },
  {
    id: "school-epistemology",
    title: "Epistemology",
    slug: "epistemology",
    thaiTitle: "ญาณวิทยา / ทฤษฎีความรู้",
    aliases: ["Epistemology", "ญาณวิทยา", "ญาณวิทยา / ทฤษฎีความรู้", "ทฤษฎีความรู้"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ญาณวิทยา / ทฤษฎีความรู้",
  },
  {
    id: "school-ethics",
    title: "Ethics",
    slug: "ethics",
    thaiTitle: "จริยศาสตร์ / ปรัชญาศีลธรรม",
    aliases: ["Ethics", "จริยศาสตร์", "จริยศาสตร์ / ปรัชญาศีลธรรม", "ปรัชญาศีลธรรม"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จริยศาสตร์ / ปรัชญาศีลธรรม",
  },
  {
    id: "school-existentialism",
    title: "Existentialism",
    slug: "existentialism",
    thaiTitle: "อัตถิภาวนิยม / อับเซิร์ดดิสม์",
    aliases: ["Existentialism", "อัตถิภาวนิยม", "อัตถิภาวนิยม / อับเซิร์ดดิสม์", "อับเซิร์ดดิสม์"],
    nodeType: "school",
    description: "สำนักคิด/สาย: อัตถิภาวนิยม / อับเซิร์ดดิสม์",
  },
  {
    id: "school-family-systems",
    title: "Family Systems",
    slug: "family-systems",
    thaiTitle: "ทฤษฎีระบบครอบครัวและการบำบัด",
    aliases: ["Family Systems", "ทฤษฎีระบบครอบครัวและการบำบัด"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ทฤษฎีระบบครอบครัวและการบำบัด",
  },
  {
    id: "school-feminist-philosophy",
    title: "Feminist Philosophy",
    slug: "feminist-philosophy",
    thaiTitle: "ปรัชญาเฟมินิสต์",
    aliases: ["Feminist Philosophy", "ปรัชญาเฟมินิสต์"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาเฟมินิสต์",
  },
  {
    id: "school-hellenistic-philosophy",
    title: "Hellenistic Philosophy",
    slug: "hellenistic-philosophy",
    thaiTitle: "ปรัชญาเฮลเลนิสติก",
    aliases: ["Hellenistic Philosophy", "ปรัชญาเฮลเลนิสติก"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาเฮลเลนิสติก",
  },
  {
    id: "school-hermeneutics",
    title: "Hermeneutics",
    slug: "hermeneutics",
    thaiTitle: "ศาสตร์แห่งการตีความ",
    aliases: ["Hermeneutics", "ศาสตร์แห่งการตีความ"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ศาสตร์แห่งการตีความ",
  },
  {
    id: "school-humanistic-psychology",
    title: "Humanistic Psychology",
    slug: "humanistic-psychology",
    thaiTitle: "จิตวิทยามนุษยนิยม",
    aliases: ["Humanistic Psychology", "จิตวิทยามนุษยนิยม"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จิตวิทยามนุษยนิยม",
  },
  {
    id: "school-ifs",
    title: "IFS",
    slug: "ifs",
    thaiTitle: "จิตบำบัดระบบครอบครัวภายใน (IFS)",
    aliases: ["IFS", "จิตบำบัดระบบครอบครัวภายใน", "จิตบำบัดระบบครอบครัวภายใน (IFS)"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จิตบำบัดระบบครอบครัวภายใน (IFS)",
  },
  {
    id: "school-indian-philosophy",
    title: "Indian Philosophy",
    slug: "indian-philosophy",
    thaiTitle: "ปรัชญาอินเดีย",
    aliases: ["Indian Philosophy", "ปรัชญาอินเดีย"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาอินเดีย",
  },
  {
    id: "school-indigenous-philosophy",
    title: "Indigenous Philosophy",
    slug: "indigenous-philosophy",
    thaiTitle: "ปรัชญาชนเผ่าพื้นเมือง",
    aliases: ["Indigenous Philosophy", "ปรัชญาชนเผ่าพื้นเมือง"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาชนเผ่าพื้นเมือง",
  },
  {
    id: "school-islamic-philosophy",
    title: "Islamic Philosophy",
    slug: "islamic-philosophy",
    thaiTitle: "ปรัชญาอิสลาม",
    aliases: ["Islamic Philosophy", "ปรัชญาอิสลาม"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาอิสลาม",
  },
  {
    id: "school-jewish-philosophy",
    title: "Jewish Philosophy",
    slug: "jewish-philosophy",
    thaiTitle: "ปรัชญายิว",
    aliases: ["Jewish Philosophy", "ปรัชญายิว"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญายิว",
  },
  {
    id: "school-lacanian-psychoanalysis-thinkers-reference-list",
    title: "Lacanian Psychoanalysis",
    slug: "lacanian-psychoanalysis-thinkers-reference-list",
    thaiTitle: "จิตวิเคราะห์แนวลากอง",
    aliases: ["Lacanian Psychoanalysis", "Lacanian", "Lacanian Psychoanalysis Thinkers Reference List", "จิตวิเคราะห์แนวลากอง"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จิตวิเคราะห์แนวลากอง",
  },
  {
    id: "school-metaphysics",
    title: "Metaphysics",
    slug: "metaphysics",
    thaiTitle: "อภิปรัชญา",
    aliases: ["Metaphysics", "อภิปรัชญา"],
    nodeType: "school",
    description: "สำนักคิด/สาย: อภิปรัชญา",
  },
  {
    id: "school-narrative-psychology",
    title: "Narrative Psychology",
    slug: "narrative-psychology",
    thaiTitle: "จิตวิทยาเชิงเล่าเรื่อง",
    aliases: ["Narrative Psychology", "จิตวิทยาเชิงเล่าเรื่อง"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จิตวิทยาเชิงเล่าเรื่อง",
  },
  {
    id: "school-neuroscience",
    title: "Neuroscience",
    slug: "neuroscience",
    thaiTitle: "ประสาทวิทยาศาสตร์ / ประสาทจิตวิเคราะห์",
    aliases: ["Neuroscience", "ประสาทจิตวิเคราะห์", "ประสาทวิทยาศาสตร์", "ประสาทวิทยาศาสตร์ / ประสาทจิตวิเคราะห์"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ประสาทวิทยาศาสตร์ / ประสาทจิตวิเคราะห์",
  },
  {
    id: "school-object-relations",
    title: "Object Relations",
    slug: "object-relations",
    thaiTitle: "ทฤษฎีความสัมพันธ์เชิงวัตถุ",
    aliases: ["Object Relations", "ทฤษฎีความสัมพันธ์เชิงวัตถุ"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ทฤษฎีความสัมพันธ์เชิงวัตถุ",
  },
  {
    id: "school-personality-psychology",
    title: "Personality Psychology",
    slug: "personality-psychology",
    thaiTitle: "จิตวิทยาบุคลิกภาพ",
    aliases: ["Personality Psychology", "จิตวิทยาบุคลิกภาพ"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จิตวิทยาบุคลิกภาพ",
  },
  {
    id: "school-phenomenology",
    title: "Phenomenology",
    slug: "phenomenology",
    thaiTitle: "ปรากฏการณ์วิทยา",
    aliases: ["Phenomenology", "ปรากฏการณ์วิทยา"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรากฏการณ์วิทยา",
  },
  {
    id: "school-phenomenology-of-psyche",
    title: "Phenomenology of Psyche",
    slug: "phenomenology-of-psyche",
    thaiTitle: "ปรากฏการณ์วิทยาแห่งจิต",
    aliases: ["Phenomenology of Psyche", "Phenomenology Of psyche", "ปรากฏการณ์วิทยาแห่งจิต"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรากฏการณ์วิทยาแห่งจิต",
  },
  {
    id: "school-philosophy-of-language",
    title: "Philosophy of Language",
    slug: "philosophy-of-language",
    thaiTitle: "ปรัชญาภาษา",
    aliases: ["Philosophy of Language", "ปรัชญาภาษา"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาภาษา",
  },
  {
    id: "school-philosophy-of-mind",
    title: "Philosophy of Mind",
    slug: "philosophy-of-mind",
    thaiTitle: "ปรัชญาแห่งจิต",
    aliases: ["Philosophy of Mind", "ปรัชญาแห่งจิต"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาแห่งจิต",
  },
  {
    id: "school-philosophy-of-race",
    title: "Philosophy of Race",
    slug: "philosophy-of-race",
    thaiTitle: "ปรัชญาเรื่องชาติพันธุ์",
    aliases: ["Philosophy of Race", "ปรัชญาเรื่องชาติพันธุ์"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาเรื่องชาติพันธุ์",
  },
  {
    id: "school-philosophy-of-religion",
    title: "Philosophy of Religion",
    slug: "philosophy-of-religion",
    thaiTitle: "ปรัชญาศาสนา",
    aliases: ["Philosophy of Religion", "ปรัชญาศาสนา"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาศาสนา",
  },
  {
    id: "school-philosophy-of-science",
    title: "Philosophy of Science",
    slug: "philosophy-of-science",
    thaiTitle: "ปรัชญาวิทยาศาสตร์",
    aliases: ["Philosophy of Science", "ปรัชญาวิทยาศาสตร์"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาวิทยาศาสตร์",
  },
  {
    id: "school-philosophy-of-technology",
    title: "Philosophy of Technology",
    slug: "philosophy-of-technology",
    thaiTitle: "ปรัชญาเทคโนโลยี",
    aliases: ["Philosophy of Technology", "ปรัชญาเทคโนโลยี"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาเทคโนโลยี",
  },
  {
    id: "school-platonism",
    title: "Platonism",
    slug: "platonism",
    thaiTitle: "ลัทธิเพลโต",
    aliases: ["Platonism", "ลัทธิเพลโต"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ลัทธิเพลโต",
  },
  {
    id: "school-political-philosophy",
    title: "Political Philosophy",
    slug: "political-philosophy",
    thaiTitle: "ปรัชญาการเมือง",
    aliases: ["Political Philosophy", "ปรัชญาการเมือง"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาการเมือง",
  },
  {
    id: "school-positivism",
    title: "Positivism",
    slug: "positivism",
    thaiTitle: "ปฏิฐานนิยม",
    aliases: ["Positivism", "ปฏิฐานนิยม"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปฏิฐานนิยม",
  },
  {
    id: "school-postcolonial-philosophy",
    title: "Postcolonial Philosophy",
    slug: "postcolonial-philosophy",
    thaiTitle: "ปรัชญาหลังอาณานิคม",
    aliases: ["Postcolonial Philosophy", "ปรัชญาหลังอาณานิคม"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญาหลังอาณานิคม",
  },
  {
    id: "school-posthumanism",
    title: "Posthumanism",
    slug: "posthumanism",
    thaiTitle: "แนวคิดหลังมนุษยนิยม",
    aliases: ["Posthumanism", "แนวคิดหลังมนุษยนิยม"],
    nodeType: "school",
    description: "สำนักคิด/สาย: แนวคิดหลังมนุษยนิยม",
  },
  {
    id: "school-pragmatism",
    title: "Pragmatism",
    slug: "pragmatism",
    thaiTitle: "ปฏิบัตินิยม",
    aliases: ["Pragmatism", "ปฏิบัตินิยม"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปฏิบัตินิยม",
  },
  {
    id: "school-process-philosophy",
    title: "Process Philosophy",
    slug: "process-philosophy",
    thaiTitle: "ปรัชญากระบวนการ",
    aliases: ["Process Philosophy", "ปรัชญากระบวนการ"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ปรัชญากระบวนการ",
  },
  {
    id: "school-psychoanalysis",
    title: "Psychoanalysis",
    slug: "psychoanalysis",
    thaiTitle: "จิตวิเคราะห์แนวฟรอยด์",
    aliases: ["Psychoanalysis", "Freudian", "จิตวิเคราะห์", "จิตวิเคราะห์แนวฟรอยด์"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จิตวิเคราะห์แนวฟรอยด์",
  },
  {
    id: "school-psychology-of-religion",
    title: "Psychology of Religion",
    slug: "psychology-of-religion",
    thaiTitle: "จิตวิทยาศาสนา",
    aliases: ["Psychology of Religion", "จิตวิทยาศาสนา"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จิตวิทยาศาสนา",
  },
  {
    id: "school-queer-theory",
    title: "Queer Theory",
    slug: "queer-theory",
    thaiTitle: "ทฤษฎีเควียร์ / เพศสภาพศึกษา",
    aliases: ["Queer Theory", "ทฤษฎีเควียร์", "ทฤษฎีเควียร์ / เพศสภาพศึกษา", "เพศสภาพศึกษา"],
    nodeType: "school",
    description: "สำนักคิด/สาย: ทฤษฎีเควียร์ / เพศสภาพศึกษา",
  },
  {
    id: "school-social-psychology",
    title: "Social Psychology",
    slug: "social-psychology",
    thaiTitle: "จิตวิทยาสังคม",
    aliases: ["Social Psychology", "จิตวิทยาสังคม"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จิตวิทยาสังคม",
  },
  {
    id: "school-structuralism",
    title: "Structuralism",
    slug: "structuralism",
    thaiTitle: "โครงสร้างนิยม / หลังโครงสร้างนิยม",
    aliases: ["Structuralism", "หลังโครงสร้างนิยม", "โครงสร้างนิยม", "โครงสร้างนิยม / หลังโครงสร้างนิยม"],
    nodeType: "school",
    description: "สำนักคิด/สาย: โครงสร้างนิยม / หลังโครงสร้างนิยม",
  },
  {
    id: "school-transpersonal",
    title: "Transpersonal",
    slug: "transpersonal",
    thaiTitle: "จิตวิทยาข้ามบุคคล",
    aliases: ["Transpersonal", "จิตวิทยาข้ามบุคคล"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จิตวิทยาข้ามบุคคล",
  },
  {
    id: "school-trauma-somatic-dissociation",
    title: "Trauma / Somatic / Dissociation",
    slug: "trauma-somatic-dissociation",
    thaiTitle: "จิตวิทยาบาดแผลทางใจและกายสัมผัส",
    aliases: ["Trauma / Somatic / Dissociation", "Trauma Somatic Dissociation", "จิตวิทยาบาดแผลทางใจและกายสัมผัส"],
    nodeType: "school",
    description: "สำนักคิด/สาย: จิตวิทยาบาดแผลทางใจและกายสัมผัส",
  },
];

export const conceptRegistry: ConceptRegistryItem[] = [
  {
    id: "concept-psyche",
    title: "Psyche",
    slug: "psyche",
    thaiTitle: "ไซคี",
    aliases: ["Psyche", "ไซคี", "psukhe"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "ระบบชีวิตทางจิตทั้งหมด ทั้งส่วนที่รู้ตัวและไม่รู้ตัว",
  },
  {
    id: "concept-ego",
    title: "Ego",
    slug: "ego",
    thaiTitle: "อัตตา",
    aliases: ["Ego", "อัตตา"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "ศูนย์กลางของจิตสำนึก",
  },
  {
    id: "concept-shadow",
    title: "Shadow",
    slug: "shadow",
    thaiTitle: "เงา",
    aliases: ["Shadow", "เงา", "Jungian Shadow"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "ส่วนของชีวิตภายในที่ Ego ไม่ต้องการรับรู้หรือยอมรับ",
  },
  {
    id: "concept-persona",
    title: "Persona",
    slug: "persona",
    thaiTitle: "หน้ากากทางสังคม",
    aliases: ["Persona", "หน้ากากทางสังคม"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "ภาพที่บุคคลแสดงต่อโลกภายนอก",
  },
  {
    id: "concept-self",
    title: "Self",
    slug: "self",
    thaiTitle: "ตัวตนทั้งหมด",
    aliases: ["Self", "ตัวตนทั้งหมด", "Selbst"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "ภาพรวมของชีวิตทางจิต ไม่ใช่เพียง Ego",
  },
  {
    id: "concept-unconscious",
    title: "Unconscious",
    slug: "unconscious",
    thaiTitle: "จิตไร้สำนึก",
    aliases: ["Unconscious", "จิตไร้สำนึก"],
    nodeType: "concept",
    description: "ส่วนของจิตที่อยู่นอกการรู้ตัว",
  },
  {
    id: "concept-collective-unconscious",
    title: "Collective Unconscious",
    slug: "collective-unconscious",
    thaiTitle: "จิตไร้สำนึกร่วม",
    aliases: ["Collective Unconscious", "จิตไร้สำนึกร่วม"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "ชั้นของจิตไร้สำนึกที่มนุษย์มีร่วมกัน",
  },
  {
    id: "concept-individuation",
    title: "Individuation",
    slug: "individuation",
    thaiTitle: "กระบวนการปัจเจกภาพ",
    aliases: ["Individuation", "กระบวนการปัจเจกภาพ"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "กระบวนการที่ชีวิตภายในค่อย ๆ จัดความสัมพันธ์ของตัวเอง",
  },
  {
    id: "concept-archetype",
    title: "Archetype",
    slug: "archetype",
    thaiTitle: "แบบฉบับดั้งเดิม",
    aliases: ["Archetype", "แบบฉบับดั้งเดิม"],
    nodeType: "concept",
    framework: "Analytical Psychology",
    description: "แบบแผนร่วมที่ปรากฏซ้ำในจิตไร้สำนึกและตำนาน",
  },
  {
    id: "term-libido",
    title: "Libido",
    slug: "libido",
    thaiTitle: "ลิบิโด",
    aliases: ["Libido", "ลิบิโด"],
    nodeType: "term",
    description: "พลังงานทางจิต (ความหมายต่างกันระหว่าง Freud และ Jung)",
  },
  {
    id: "person-carl-jung",
    title: "Carl Jung",
    slug: "carl-jung",
    thaiTitle: "คาร์ล ยุง",
    aliases: ["Carl Jung", "C. G. Jung", "Jung", "ยุง", "คาร์ล ยุง"],
    nodeType: "person",
    framework: "Analytical Psychology",
    description: "นักจิตวิทยาผู้วางรากฐานจิตวิทยาวิเคราะห์",
  },
  {
    id: "person-sigmund-freud",
    title: "Sigmund Freud",
    slug: "sigmund-freud",
    thaiTitle: "ซิกมุนด์ ฟรอยด์",
    aliases: ["Sigmund Freud", "Freud", "ฟรอยด์"],
    nodeType: "person",
    framework: "Psychoanalysis",
    description: "ผู้วางรากฐานจิตวิเคราะห์",
  },
  {
    id: "book-psychological-types",
    title: "Psychological Types",
    slug: "psychological-types",
    aliases: ["Psychological Types"],
    nodeType: "book",
    framework: "Analytical Psychology",
    description: "งานสำคัญของ Jung ว่าด้วยประเภททางจิตวิทยา",
  },
  ...schoolRegistry,
];

export function getConceptBySlug(slug: string): ConceptRegistryItem | undefined {
  return conceptRegistry.find((c) => c.slug === slug);
}

// resolve โดยลำดับ: slug → title → thaiTitle → alias (กันสร้าง node ซ้ำ)
export function resolveConcept(input: string): ConceptRegistryItem | undefined {
  const q = input.trim().toLowerCase();
  return (
    conceptRegistry.find((c) => c.slug.toLowerCase() === q) ||
    conceptRegistry.find((c) => c.title.toLowerCase() === q) ||
    conceptRegistry.find((c) => (c.thaiTitle ?? "").toLowerCase() === q) ||
    conceptRegistry.find((c) => c.aliases.some((a) => a.toLowerCase() === q))
  );
}

export function conceptTitle(slug: string): string {
  return getConceptBySlug(slug)?.title ?? slug;
}
